import React from 'react';
import {Panel,Icon,Button,DetailLink,Empty} from './UI.jsx';
import {stages,regions,orders,inRegion,money,slaData} from '../data.js';
export function Business({data,open}){
 return <Panel title="业务全链路" en="Business" icon="business" id="business" action={<DetailLink onClick={()=>open({type:'orders'})}/>}>
  <div className="pipeline">{stages.map((s,i)=><button key={s} onClick={()=>open({type:'stage',stage:i})}><span className="stage-icon"><Icon name={['message','file','wallet','package','send','money'][i]}/></span><span className="stage-name">{s}</span><strong>{data.pipeline[i]}</strong></button>)}</div>
  <div className="subheading"><span><i className="status-dot red"/>异常预警 <b>{data.risks.length.toString().padStart(2,'0')}</b></span><DetailLink onClick={()=>open({type:'risks'})}>全部风险</DetailLink></div>
  <div className="risk-list">{data.risks.slice(0,2).map(o=><button key={o.id} className="risk-row" onClick={()=>open({type:'risk',id:o.id})}><Icon name="warning" size={17}/><div><strong>{o.risk==='lc'?'德国客户 · 信用证单据不符':o.risk==='overdue'?'美国客户 · 尾款逾期 12 天':`${o.customer} · 订单停滞`}</strong><small>{o.id} <span>USD {money(o.amount)}</span></small></div><span className="risk-level">高危</span><Icon name="chevron" size={14}/></button>)}{!data.risks.length&&<Empty/>}</div>
 </Panel>;
}
export function Team({data,open,reassign}){
 const overdue=data.team.reduce((s,t)=>s+t.overdue.length+t.stalled.length,0);
 return <Panel title="团队效能" en="Team" icon="users" id="team" action={<span className={`panel-note ${overdue?'warning-text':''}`}>{overdue} 项待跟进</span>}><table className="team-table"><thead><tr><th>业务员</th><th>商机</th><th>平均首响</th><th>转化率</th><th>操作</th></tr></thead><tbody>{data.team.map(t=><tr key={t.name}><td><span className="avatar">{t.name.slice(-1)}</span>{t.name}</td><td>{t.count}</td><td>{t.response.toFixed(1)}h {t.overdue.length>0&&<span className="overdue-count">{t.overdue.length} 超时</span>}</td><td>{t.conversion.toFixed(1)}%</td><td>{t.overdue.length+t.stalled.length>0?<button className="text-action" onClick={()=>reassign(t.name)}>重分配</button>:<span className="normal">正常</span>}</td></tr>)}</tbody></table><button className="table-foot" onClick={()=>open({type:'team'})}><Icon name="clock" size={12}/>首响 &gt;4h 或订单停滞 &gt;7天自动预警<Icon name="chevron" size={12}/></button></Panel>;
}
export function Customer({data,open,journey}){
 const tiers=['A','B','C'].map(t=>({name:t,count:data.customers.filter(c=>c.tier===t).length}));
 const a=tiers[0].count/data.customers.length*100||0,b=tiers[1].count/data.customers.length*100||0;
 const remaining=data.dormant.filter(c=>!journey.includes(c.id)).length;
 return <Panel title="客户资产" en="Customer" icon="user" id="customer" action={<DetailLink onClick={()=>open({type:'customers'})}/>}><div className="customer-chart"><button className="donut" aria-label="查看客户分层" onClick={()=>open({type:'customers'})} style={{background:`conic-gradient(#2584ff 0 ${a}%,#2ddeed ${a}% ${a+b}%,#80caff ${a+b}% 100%)`}}><span><strong>{data.customers.length}</strong><small>活跃客户</small></span></button><div className="tier-legend">{tiers.map((t,i)=><button key={t.name} onClick={()=>open({type:'customers',tier:t.name})}><i style={{background:['#2584ff','#2ddeed','#80caff'][i]}}/><span>{t.name} 类 <small>{['战略客户','重点客户','长尾客户'][i]}</small></span><strong>{t.count}</strong><em>{(t.count/data.customers.length*100||0).toFixed(1)}%</em></button>)}</div></div><div className={`dormant ${remaining?'':'done'}`}><Icon name={remaining?'warning':'check'} size={22}/><div><strong>{remaining?'60 天以上未复购':'唤醒计划已创建'}</strong><small>{data.dormant.length} 位老客 · {remaining} 位待加入旅程</small></div><Button onClick={()=>open({type:'journey'})}>唤醒旅程</Button></div></Panel>;
}
export function Traffic({data,open}){
 return <Panel title="流量质量" en="Traffic" icon="chart" id="traffic" action={<DetailLink onClick={()=>open({type:'traffic'})}>渠道分析</DetailLink>}><div className="traffic-head"><span>获客渠道</span><span>询盘 / 商机</span><span>转化率</span></div><div className="channel-list">{data.traffic.map(t=><button key={t.name} onClick={()=>open({type:'traffic',channel:t.name})}><span className="channel-name">{t.name}{t.warning&&<i className="status-dot amber"/>}</span><span className="channel-bar"><i style={{width:`${t.conversion/40*100}%`}}/><b>{t.count}</b></span><strong className={t.warning?'warning-text':''}>{t.conversion.toFixed(1)}%</strong></button>)}</div><div className="traffic-foot"><span><i className="status-dot amber"/>转化率 &lt;20% / CTR &lt;3% 预警</span><span>点击查看诊断</span></div></Panel>;
}
export function Globe({data,region,setRegion,open}){
 const dims=[['业务','business'],['团队','team'],['客户','customer'],['流量','traffic'],['结构','structure'],['效率','efficiency']];
 return <section className="globe-panel"><div className="globe-top"><div><span className="live-dot"/>全球业务态势</div><label><Icon name="filter" size={13}/><select aria-label="区域联动筛选" value={region} onChange={e=>setRegion(e.target.value)}>{regions.map(r=><option key={r}>{r}</option>)}</select></label></div><div className="globe-stage"><img src={`${import.meta.env.BASE_URL}assets/globe.png`} alt="蓝色全息地球，全球贸易网络连接示意"/><div className="orbital-ring"/><div className="globe-coordinate top-coordinate">GLOBAL BUSINESS NETWORK</div><div className="globe-coordinate bottom-coordinate"><span className="live-dot"/> 六大维度 · 协同洞察</div>{dims.map(([label,key],i)=><button className={`dimension dim-${i}`} key={key} onClick={()=>{document.getElementById(key)?.scrollIntoView({behavior:'smooth',block:'nearest'});open({type:key==='business'?'orders':key==='customer'?'customers':key});}}><span><Icon name={{business:'business',team:'users',customer:'user',traffic:'chart',structure:'layers',efficiency:'gauge'}[key]} size={21}/></span><b>{label}</b></button>)}</div><div className="globe-stats"><div><strong>{new Set(data.customers.map(c=>c.country)).size}</strong><span>覆盖国家与地区</span></div><div><strong>{data.customers.length}</strong><span>活跃客户</span></div><div><strong>{data.orders.length}</strong><span>执行中订单</span></div><div><strong>{(data.revenue/1e6).toFixed(2)}<small>M</small></strong><span>订单金额 / USD</span></div></div></section>;
}
export function Structure({data,region,setRegion,open}){
 const totals=regions.slice(1).map(r=>({name:r,amount:inRegion(orders,r).reduce((s,o)=>s+o.amount,0)}));
 const total=orders.reduce((s,o)=>s+o.amount,0);
 return <Panel title="出口结构" en="Structure" icon="globe" id="structure" action={<DetailLink onClick={()=>open({type:'structure'})}>风险敞口</DetailLink>}><div className="structure-grid"><div className="region-bars">{totals.map(r=><button key={r.name} className={region===r.name?'selected':''} onClick={()=>setRegion(region===r.name?'全球':r.name)}><span>{r.name}</span><i><b style={{width:`${r.amount/Math.max(...totals.map(x=>x.amount))*100}%`}}/></i><strong>{(r.amount/total*100).toFixed(1)}%</strong></button>)}</div><div className="settlement"><div className="settlement-label">结算方式与风险 <small>{region} · 合同金额口径</small></div><div className="stacked">{data.settlements.map((s,i)=><button aria-label={`${s.name}结算详情`} key={s.name} style={{width:`${s.amount/data.revenue*100}%`,background:['#228fff','#24cfda','#eac568'][i]}} onClick={()=>open({type:'structure',settlement:s.name})}/>)}</div><div className="settlement-legend">{data.settlements.map((s,i)=><span key={s.name}><i style={{background:['#228fff','#24cfda','#eac568'][i]}}/>{s.name} <b>{(s.amount/data.revenue*100||0).toFixed(1)}%</b></span>)}</div><button className="insurance" onClick={()=>open({type:'structure'})}><Icon name="shield" size={25}/><span>关注赊销与信用证风险<small>查看敞口明细与信保资料清单</small></span><Icon name="chevron" size={15}/></button></div></div></Panel>;
}
export function Efficiency({open,aiTasks}){
 return <Panel title="SLA 效率" en="Efficiency" icon="gauge" id="efficiency" action={<span className="panel-note">全公司 · 演示基准</span>}><div className="sla-nodes">{slaData.map(s=><button key={s.name} className={s.current>s.target?'late':''} onClick={()=>open({type:'efficiency',node:s.name})}><span className="sla-icon"><Icon name={s.icon}/></span><span>{s.name}</span><small>目标 ≤{s.target}{s.unit}</small><strong>{s.current}<em>{s.unit}</em></strong></button>)}</div><div className="sla-summary"><span>节点达标率 <strong>{(slaData.reduce((s,n)=>s+n.rate,0)/slaData.length).toFixed(1)}<small>%</small></strong></span><Button icon="sparkles" onClick={()=>open({type:'efficiency'})}>{aiTasks?'查看提效计划':'AI 辅助提效'}</Button></div></Panel>;
}
