import React,{useState} from 'react';
import {Modal,Button,Icon,Empty} from './UI.jsx';
import {money,stages,slaData} from '../data.js';
const riskCopy={
 lc:{title:'德国客户 · 信用证单据不符点',context:'示例：商业发票货描与信用证条款不一致，装运日期需要复核。',steps:['核对信用证及全部修改书，列出单证差异与交单期限。','交由单证人员复核发票、装箱单和提单的一致性。','联系银行核实可行处理路径；如需改单或接受不符点，由授权人员确认。','保存处理记录，核对更正后的单据后再安排交单。']},
 overdue:{title:'美国客户 · 尾款逾期 12 天',context:'示例：提单到港后，尾款仍未到账。该预警需结合合同到期日、银行流水和货权状态核实。',steps:['核实约定付款日及银行到账记录，确认应收差额。','业务员联系客户取得书面付款计划，并记录争议原因。','由财务、物流共同核实货权和提货状态，升级内部审批。','检查信保保单约定的通知期限，必要时咨询保险机构。']},
 stalled:{title:'订单停滞 · 跟进预警',context:'示例：订单节点超过 7 天无推进记录。',steps:['核实当前订单节点与最后一次跟进记录。','定位客户确认、生产排期或单证环节的阻塞。','指定处理负责人和下一次跟进日期。','更新订单状态并保留处置记录。']}
};
function OrderTable({items,onOpen}){return <div className="table-scroll"><table className="detail-table"><thead><tr><th>订单编号</th><th>区域 / 客户</th><th>阶段</th><th>金额 USD</th><th>结算</th></tr></thead><tbody>{items.map(o=><tr key={o.id}><td><button className="text-action" onClick={()=>onOpen({type:'risk',id:o.id})}>{o.id}</button></td><td>{o.customer}</td><td>{stages[o.stage]}</td><td>{money(o.amount)}</td><td>{o.settlement}</td></tr>)}</tbody></table>{!items.length&&<Empty>当前范围内暂无订单</Empty>}</div>;}
export default function Details({selection,data,onClose,open,handled,handleRisk,reassign,journey,startJourney,aiTasks,createAI,region}){
 const [tier,setTier]=useState(selection.tier||'全部');
 const [channel,setChannel]=useState(selection.channel||'全部');
 const type=selection.type;
 const titles={orders:'业务订单 · 全链路追踪',stage:`${stages[selection.stage]} · 节点明细`,risks:'高危异常 · 处理中心',team:'团队跟进 · SLA 预警',customers:'客户资产 · A/B/C 分层',journey:'老客唤醒 · 自动化旅程',traffic:'渠道转化 · 质量诊断',structure:'出口结构 · 结算风险敞口',efficiency:'AI 辅助提效 · SLA 工作台'};
 const order=data.orders.find(o=>o.id===selection.id);
 let title=titles[type]||'订单详情';
 if(type==='risk'&&order)title=order.risk?riskCopy[order.risk].title:'订单详情';
 const remaining=data.dormant.filter(c=>!journey.includes(c.id));
 return <Modal title={title} subtitle={`${region} · 演示数据 / 操作仅保存于当前浏览器`} onClose={onClose}>
 {type==='risk'&&order&&<><div className="detail-banner"><Icon name={order.risk?'warning':'package'} size={28}/><div><strong>{order.id}</strong><span>{order.customer} · {order.owner} · {order.settlement}</span></div><b>USD {money(order.amount)}</b></div><div className="detail-pipeline">{stages.map((s,i)=><span key={s} className={i<=order.stage?'passed':''}><Icon name={i<order.stage?'check':i===order.stage?'target':'clock'} size={14}/>{s}</span>)}</div>{order.risk?<><p>{riskCopy[order.risk].context}</p><h3>建议处理路径</h3><ol className="action-steps">{riskCopy[order.risk].steps.map(s=><li key={s}>{s}</li>)}</ol><p className="fine-print">此处为演示处置模板。实际审单、回款及保险处理应以合同、银行和保险机构核实结果为准。</p><Button icon="check" disabled={handled.includes(order.id)} onClick={()=>handleRisk(order.id)}>{handled.includes(order.id)?'已加入处理计划':'加入处理计划（演示）'}</Button><p className="fine-print">加入后从“待处理风险”移出，表示已受理，不代表订单风险已解除。</p></>:<p>当前节点：{stages[order.stage]}。此订单暂无风险预警。</p>}</>}
 {type==='risk'&&!order&&<Empty>该订单不在当前筛选范围内</Empty>}
 {(type==='orders'||type==='risks'||type==='stage')&&<><div className="detail-banner"><Icon name="business"/><span>{type==='risks'?`${data.risks.length} 笔待处理异常`:type==='stage'?`当前节点累计进入量 ${data.pipeline[selection.stage]}`:`${data.orders.length} 笔执行中订单`}</span><small>统计范围：{region}</small></div>{type==='stage'&&selection.stage<2?<><p>{selection.stage===0?'询盘与 RFQ 商机按线索口径展示。':'已转化商机作为报价 PI 阶段的演示样本。'}</p><div className="table-scroll"><table className="detail-table"><thead><tr><th>线索</th><th>渠道</th><th>负责人</th><th>首响</th></tr></thead><tbody>{data.leads.filter(l=>selection.stage===0||l.converted).map(l=><tr key={l.id}><td>{l.id}</td><td>{l.channel}</td><td>{l.owner}</td><td>{l.response.toFixed(1)}h</td></tr>)}</tbody></table></div></>:<OrderTable items={type==='risks'?data.risks:type==='stage'?data.orders.filter(o=>o.stage>=selection.stage):data.orders} onOpen={open}/>}</>}
 {type==='team'&&<><p>首响超过 4 小时或订单停滞超过 7 天进入待跟进队列。一键重分配给当前范围内商机负载最低的其他业务员。</p>{data.team.map(t=><div className="team-detail" key={t.name}><div><strong>{t.name}</strong><small>{t.count} 个商机 · 转化率 {t.conversion.toFixed(1)}%</small></div><span className={t.overdue.length+t.stalled.length?'red-text':''}>{t.overdue.length} 条首响超时 / {t.stalled.length} 笔停滞</span><Button disabled={!t.overdue.length&&!t.stalled.length} onClick={()=>reassign(t.name)}>一键重分配</Button></div>)}<p className="fine-print">重分配仅变更演示负责人，原始首响耗时保留，不会伪造已回复状态。</p></>}
 {type==='customers'&&<><div className="tabs">{['全部','A','B','C'].map(t=><button key={t} className={tier===t?'active':''} onClick={()=>setTier(t)}>{t==='全部'?t:`${t} 类客户`}</button>)}</div><div className="table-scroll"><table className="detail-table"><thead><tr><th>客户</th><th>分层</th><th>距上次复购</th><th>唤醒状态</th></tr></thead><tbody>{data.customers.filter(c=>tier==='全部'||c.tier===tier).map(c=><tr key={c.id}><td>{c.name}</td><td>{c.tier} 类</td><td className={c.days>60?'red-text':''}>{c.days} 天</td><td>{journey.includes(c.id)?'已建唤醒计划':c.days>60?'待唤醒':'正常'}</td></tr>)}</tbody></table></div></>}
 {type==='journey'&&<><div className="detail-banner"><Icon name="users"/><div><strong>{data.dormant.length} 位沉睡客户</strong><span>距上次复购超过 60 天 · {remaining.length} 位待加入</span></div></div><div className="journey-steps">{[['第 1 天','需求回访','核实历史采购与当前库存，起草个性化回访邮件。'],['第 3 天','产品匹配','根据客户历史品类，准备新品或补货建议。'],['第 7 天','人工跟进','有回复转交业务员；未回复进入人工评估队列。']].map(([day,name,desc])=><div key={day}><span>{day}</span><strong>{name}</strong><p>{desc}</p></div>)}</div><p className="fine-print">此按钮创建本地计划。未接入邮件或 CRM，不会自动联系客户；发送前需审核收件人、内容和授权。</p><Button icon="send" disabled={!remaining.length} onClick={startJourney}>{remaining.length?`为 ${remaining.length} 位客户创建唤醒计划`:'当前客户均已加入计划'}</Button>{!!journey.length&&<div className="success-box"><Icon name="check"/>本地唤醒计划已保存，可关闭后重新查看。</div>}</>}
 {type==='traffic'&&<><div className="tabs">{['全部',...data.traffic.map(t=>t.name)].map(c=><button key={c} className={channel===c?'active':''} onClick={()=>setChannel(c)}>{c}</button>)}</div>{data.traffic.filter(t=>channel==='全部'||t.name===channel).map(t=><div className="channel-detail" key={t.name}><h3>{t.name}<span className={t.warning?'warning-text':'normal'}>{t.warning?'需优化':'质量正常'}</span></h3><div className="detail-stats"><div><strong>{money(t.views)}</strong><span>点击量</span></div><div><strong>{t.ctr.toFixed(2)}%</strong><span>CTR</span></div><div><strong>{t.count}</strong><span>商机数</span></div><div><strong>{t.conversion.toFixed(1)}%</strong><span>商机转化率</span></div></div><p>{t.warning?'建议排查关键词与受众匹配度、落地页信息一致性，以及线索首响是否超时。调整后用相同统计周期对比有效商机率。':'当前样例转化质量达到阈值，可进一步核查成交金额和获客成本，再决定是否增加投入。'}</p></div>)}<p className="fine-print">CTR = 点击量 / 展示量；转化率 = 转化商机 / 商机总数。RFQ 与社媒指标以统一演示口径模拟，真实接入时需分别映射平台定义。</p></>}
 {type==='structure'&&<><p>按订单合同金额展示结算结构。合同金额不等于未收款余额；下方是用于展示功能的敞口代理指标。</p><div className="detail-stats">{data.settlements.map(s=><div key={s.name}><strong>${money(s.amount)}</strong><span>{s.name} · {(s.amount/data.revenue*100).toFixed(1)}%</span></div>)}</div><h3>信保投保资料准备</h3><ol className="action-steps"><li>核对买方、账期、未收款余额与现有信用额度。</li><li>准备合同、发票、出运及付款记录，检查保单责任范围和除外事项。</li><li>向保险机构核实买方限额、适用产品及申报期限，再决定投保方案。</li></ol><OrderTable items={data.orders.filter(o=>!selection.settlement||o.settlement===selection.settlement)} onOpen={open}/></>}
 {type==='efficiency'&&<><p>当前为规则模板演示，未连接 AI 模型。根据超标节点整理处理清单，供业务人员审核后执行。</p><div className="sla-detail">{slaData.filter(n=>!selection.node||n.name===selection.node).map(n=><div key={n.name}><Icon name={n.icon}/><strong>{n.name}</strong><span className={n.current>n.target?'warning-text':''}>{n.current} {n.unit} / 目标 {n.target} {n.unit}</span><span>达标率 {n.rate}%</span></div>)}</div><h3>优先提效建议</h3><ol className="action-steps"><li><b>审证：</b>整理信用证条款、交单时限与单证核验清单，由单证人员复核。</li><li><b>回款：</b>按账龄和约定付款日排序，起草催收跟进模板与责任人清单。</li><li><b>首响与报价：</b>准备询盘摘要和报价所需参数清单，减少重复录入。</li></ol><Button icon="sparkles" onClick={createAI} disabled={aiTasks}>{aiTasks?'提效计划已保存':'生成并保存提效计划（演示）'}</Button>{aiTasks&&<div className="success-box"><Icon name="check"/>已建立 3 项本地提效任务，待人工审核。</div>}</>}
 </Modal>;
}
