import React,{useState,useEffect} from 'react';
import {Metric,Icon,Button} from './components/UI.jsx';
import {Business,Team,Customer,Traffic,Globe,Structure,Efficiency} from './components/DashboardPanels.jsx';
import Details from './components/Details.jsx';
import {aggregate,getReassignment,money} from './data.js';
const STORAGE_KEY='trade-cockpit-demo-v1';
function readState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return {assignments:s.assignments&&typeof s.assignments==='object'&&!Array.isArray(s.assignments)?s.assignments:{},handled:Array.isArray(s.handled)?s.handled:[],journey:Array.isArray(s.journey)?s.journey:[],aiTasks:s.aiTasks===true};}catch{return {assignments:{},handled:[],journey:[],aiTasks:false};}}
export default function App(){
 const [state,setState]=useState(readState),[region,setRegion]=useState('全球'),[selection,setSelection]=useState(null),[toast,setToast]=useState(''),[time,setTime]=useState(new Date()),[fullscreen,setFullscreen]=useState(false),[storageFailed,setStorageFailed]=useState(false);
 const data=aggregate(region,state.assignments,state.handled);
 useEffect(()=>{const t=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(t);},[]);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));setStorageFailed(false);}catch{setStorageFailed(true);}},[state]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{const update=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update);},[]);
 function reassign(name){const result=getReassignment(data,name,state.assignments);if(!result)return;setState(s=>({...s,assignments:result.assignments}));setToast(`${result.count} 项跟进已重分配给${result.target}（本地演示）`);}
 async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else setToast('当前浏览器不支持全屏，请在独立浏览器打开。');}catch{setToast('当前浏览器限制全屏，请在独立浏览器打开。');}}
 return <div className="dashboard"><header className="topbar"><div className="datetime"><div>{time.toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'})}<span>{time.toLocaleDateString('zh-CN',{weekday:'long'})}</span></div><time>{time.toLocaleTimeString('en-GB',{hour12:false})}</time></div><div className="title-frame"><h1>外贸经营驾驶舱</h1><p>GLOBAL TRADE INTELLIGENCE</p></div><div className="header-controls"><span className="demo-badge"><i className="status-dot"/>演示数据</span><Button icon={fullscreen?'min':'max'} secondary onClick={toggleFullscreen}>{fullscreen?'退出全屏':'全屏'}</Button></div></header>
 <main><section className="metrics" aria-label="经营核心指标"><Metric icon="money" label="执行订单金额" unit="USD" value={money(data.revenue)} caption={`${region} · 合同金额口径`} onClick={()=>setSelection({type:'orders'})}/><Metric icon="file" label="执行中订单" value={data.orders.length} caption="定金 → 生产 → 出运 → 回款" onClick={()=>setSelection({type:'orders'})}/><Metric icon="users" label="活跃客户" value={data.customers.length} caption="A / B / C 分层管理" onClick={()=>setSelection({type:'customers'})}/><Metric icon="filter" label="商机转化率" value={`${data.conversion.toFixed(1)}%`} caption={`${data.leads.length} 个有效商机`} onClick={()=>setSelection({type:'traffic'})}/><Metric icon="warning" label="待处理风险" value={String(data.risks.length).padStart(2,'0')} caption="点击进入异常处理中心" danger onClick={()=>setSelection({type:'risks'})}/></section>
 <div className="main-grid"><div className="left-column"><Business data={data} open={setSelection}/><Team data={data} open={setSelection} reassign={reassign}/></div><Globe data={data} region={region} setRegion={setRegion} open={setSelection}/><div className="right-column"><Customer data={data} open={setSelection} journey={state.journey}/><Traffic data={data} open={setSelection}/></div></div>
 <div className="bottom-grid"><Structure data={data} region={region} setRegion={setRegion} open={setSelection}/><Efficiency open={setSelection} aiTasks={state.aiTasks}/></div></main>
 <footer className="footer"><span><i className="live-dot"/>{region}视图 · 六维联动</span><span className="footer-center">数据驱动决策 · 让全球生意清晰可见</span><span>{storageFailed?'本地存储不可用，刷新将丢失操作':'演示数据 · 未连接业务系统'}</span></footer>
 {selection&&<Details key={`${selection.type}-${selection.id||''}-${selection.stage??''}`} selection={selection} data={data} region={region} onClose={()=>setSelection(null)} open={setSelection} handled={state.handled} handleRisk={id=>{setState(s=>({...s,handled:[...new Set([...s.handled,id])]}));setToast('已加入本地处理计划，风险尚未解除');}} reassign={reassign} journey={state.journey} startJourney={()=>{setState(s=>({...s,journey:[...new Set([...s.journey,...data.dormant.map(c=>c.id)])]}));setToast('唤醒计划已创建，未发送任何消息');}} aiTasks={state.aiTasks} createAI={()=>{setState(s=>({...s,aiTasks:true}));setToast('已保存 3 项提效任务（规则模板演示）');}}/>}
 {toast&&<div className="toast" role="status"><Icon name="check"/>{toast}<button aria-label="关闭提示" onClick={()=>setToast('')}><Icon name="close" size={14}/></button></div>}
 </div>;
}
